data_path : "../data/AURSAD.dat"  # path of the raw time series data
data_name : "AURSAD"  # name of the dataset to save in output
output_dir_path : "../data/STAD-FEBTE"  # path of the directory of the output data
ftrs_tag : ["torque", "tcp_pose_0", "tcp_pose_1", "tcp_pose_2", "tcp_pose_3", "tcp_pose_4", "tcp_pose_5", "tcp_speed_0", "tcp_speed_1", "tcp_speed_2", "tcp_speed_3", "tcp_speed_4", "tcp_speed_5", "tcp_force_0", "tcp_force_1", "tcp_force_2", "tcp_force_3", "tcp_force_4", "tcp_force_5"]  # keys of time series in each sample
label_tag : "label"  # label key 
time_type : "fixed"  # type of the time vector in the dataset - should be in ["fixed", "varying"]
time_tag :  "time"  # key of the time vectors in each sample
catg_incl : False  # whether to include categorical features 
catg_tag : null  # key of the categorical features in each sample
n_jobs : 30  # number of CPUs involved
random_state : 42  # randome state for reproducing results

