data_path : "../data/synthetic_fixed.dat"
data_name : "synthetic_fixed"
output_dir_path : "../data/STAD-FEBTE"
ftrs_tag : ["torque", "depth"]  # should be inside a list even if single
label_tag : "label"
time_type : "fixed" 
time_tag : "time"
catg_incl : False
catg_tag : null
n_jobs : 6
random_state : 42
